.TH rpm2deb-changelog 1
.SH NAME
rpm2deb-changelog \- Transforms an RPM *.changes file into a Debian changelog.
.SH SYNOPSIS
rpm2deb-changelog [OPTIONS]

.SH DESCRIPTION
\fBrpm2deb-changelog\fR is a Perl script which transforms an RPM *.changes file
into a Debian changelog. Minor editing may be required to have a consistent
Debian changelog (versions, urgencies, ...). The aim of this script is
to simplify the life of a maintainer, who packages for both RPM-based distros
and Debian-based distros.

.SH ARGUMENTS
\fBrpm2deb-changelog\fR only has options arguments.

.SH OPTIONS
.TP
.IR -h|--help
Displays this help and exit.
.TP
.IR --version
Displays script version and exit.
.TP
.IR -d|--debug
Debug mode: maximum verbosity.
.TP
.IR -v|--verbose
Verbose mode: increased verbosity.
.TP
.IR -i|--input
Input file path (defaults to *.changes).
.TP
.IR -o|--output
Output file path (defaults to "debian.changelog").
.TP
.IR -a|--area
Distribution of the package (defaults to "unstable").
.TP
.IR -m|--maintainer
Name of the maintainer or path to a file listing maintainers (defaults to being extracted from the *.dsc file).
.TP
.IR -n|--newversion
Packaged software version (defaults to being guessed using *.dsc file).
.TP
.IR -p|--package
Package name (defaults to being guessed using *.dsc file).
.TP
.IR -u|--urgency
Revision urgency (defaults to "low").

.SH AUTHOR
The script and the man page were written by \fBPascal COMBES\fR <\fIpascom@orange.fr\fR>

.SH COPYRIGHT
\fBrpm2deb-changelog\fR is copyright 2018 \fBPascal COMBES\fR <\fIpascom@orange.fr\fR>.
All rights reserved.

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation files
(the "Software"), to deal in the Software without restriction,
including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT.  IN NO EVENT SHALL SIMON TATHAM BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
